import { expect, test } from "@playwright/test";

async function choose(page:import("@playwright/test").Page,name:RegExp){await page.goto("/login");const identity=page.getByRole("button",{name});await expect(identity).toHaveAttribute("data-ready","true");await identity.click();await expect(page).toHaveURL(/\/portal\//)}

test("role surfaces and direct routes remain restricted",async({page})=>{await choose(page,/Ali/);await expect(page.getByRole("link",{name:"My jobs"})).toBeVisible();await expect(page.getByRole("link",{name:"Dashboard"})).toHaveAttribute("href","/portal/technician-dashboard");await page.goto("/portal/dashboard");await expect(page).toHaveURL(/\/portal\/technician-dashboard/);await page.goto("/portal/orders/order-1237");await expect(page.getByText("You do not have access to this order.")).toBeVisible()});

test("checklist stores item proof and completion evidence rejects more than six files",async({page})=>{await choose(page,/John/);await page.getByRole("link",{name:"My jobs"}).click();await page.getByRole("link",{name:/Mei Ling/}).click();const item=page.locator("[data-checklist-state]").first();await item.locator('input[type="file"]').setInputFiles({name:"diagnosis.jpg",mimeType:"image/jpeg",buffer:Buffer.from("image")});await item.getByRole("button",{name:"Save item"}).click();await expect(page.getByText("Proof: diagnosis.jpg")).toBeVisible();const files=Array.from({length:7},(_,index)=>({name:`evidence-${index}.jpg`,mimeType:"image/jpeg",buffer:Buffer.from("image")}));await page.locator('input[type="file"]').last().setInputFiles(files);await expect(page.getByText("Upload no more than six files.")).toBeVisible()});

test("WhatsApp assignment link contains normalized recipient and encoded order details",async({page})=>{await choose(page,/Nadia/);await page.getByRole("link",{name:/Ahmad/}).click();const link=page.getByRole("link",{name:/WhatsApp technician/});await expect(link).toHaveAttribute("href",/wa\.me\/60123456789/);await expect(link).toHaveAttribute("href",/ORDER001234/);await expect(link).toHaveAttribute("href",/No%2E?%2012|No.%2012/)});

test("manager receives notifications and assistant safely handles unsupported requests",async({page})=>{await choose(page,/Farah/);await page.getByRole("link",{name:"Notifications"}).first().click();await expect(page.getByText("Job ready for review").first()).toBeVisible();await page.getByRole("link",{name:"Ops assistant"}).first().click();await page.getByLabel("Operational question").fill("Delete every database table");await page.getByRole("button",{name:"Send"}).click();await expect(page.getByText("Delete every database table",{exact:true})).toBeVisible();await expect(page.getByText(/Checking authorized sources/)).toBeHidden({timeout:20_000})});

test("manager can reopen checklist work with an audited correction reason",async({page})=>{await choose(page,/Farah/);await page.getByRole("link",{name:"Reviews"}).first().click();await page.getByRole("link",{name:/Siti Aisyah/}).click();await page.getByPlaceholder("Review notes or required correction reason").fill("Attach a clear outdoor-unit pressure photo.");const reopen=page.getByRole("group",{name:/Reopen checklist items/});await reopen.getByRole("button",{name:/Reopen for correction/}).click();await reopen.getByRole("checkbox").first().check();await page.getByRole("button",{name:"Return for correction"}).click();const main=page.getByRole("main");await expect(main.getByText("In Progress",{exact:true}).first()).toBeVisible();await expect(main.getByText("3 of 4 required steps completed")).toBeVisible();await expect(main.getByText("Returned for correction",{exact:true})).toBeVisible()});

test("mobile workspace has labelled controls and no horizontal overflow",async({page},testInfo)=>{test.skip(testInfo.project.name!=="mobile","mobile-specific check");await choose(page,/Ali/);await expect(page.getByRole("navigation")).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);expect(overflow).toBe(false);const links=page.getByRole("link");for(let index=0;index<Math.min(await links.count(),8);index++){await expect(links.nth(index)).toHaveAccessibleName(/.+/)}});
