import { describe, expect, it, vi } from "vitest";
import { SupabaseOperationsRepository } from "./supabase-operations";
import type { ServiceOrder } from "@/lib/domain";

const order: ServiceOrder = {
  id:"order-1",orderNo:"ORDER1",customerName:"Mei",customerPhone:"6012",address:"KL",problemDescription:"Leak",
  serviceType:"Repair",quotedPrice:260,technicianId:"tech-john",branch:"Kuala Lumpur",status:"In Progress",version:2,
  createdAt:"2026-08-14T00:00:00Z",checklist:[],reviews:[],scheduleEvents:[],audit:[],
};

function clientFixture(overrides:Record<string,unknown[]> = {}) {
  const rows:Record<string,unknown[]>={orders:[{id:"order-1",order_no:"ORDER1",customer_name:"Mei",customer_phone:"6012",address:"KL",problem_description:"Leak",service_type:"Repair",quoted_price:260,assigned_technician_id:"20000000-0000-0000-0000-000000000004",branch_id:"b1",scheduled_at:null,admin_notes:null,status:"In Progress",version:2,created_at:"2026-08-14T00:00:00Z"}],branches:[{id:"b1",name:"Kuala Lumpur"}],profiles:[{id:"20000000-0000-0000-0000-000000000004",display_name:"John"}],order_checklist_items:[],job_evidence:[],service_completions:[],payments:[],schedule_events:[],reviews:[],audit_events:[],notifications:[],...overrides};
  const rpc=vi.fn().mockResolvedValue({data:{id:"created-1"},error:null});
  const handlers:Array<()=>void>=[];
  const channel={on:vi.fn((_event,_filter,handler)=>{handlers.push(handler);return channel}),subscribe:vi.fn((callback)=>{callback("SUBSCRIBED");return channel})};
  const removeChannel=vi.fn();
  return {client:{from:vi.fn((name:string)=>({select:vi.fn().mockResolvedValue({data:rows[name],error:null}),update:vi.fn(()=>({eq:vi.fn().mockResolvedValue({error:null})}))})),rpc,channel:vi.fn(()=>channel),removeChannel},rpc,handlers,removeChannel};
}

describe("SupabaseOperationsRepository",()=>{
  it("hydrates normalized authorized rows into one domain order",async()=>{const fixture=clientFixture({order_checklist_items:[{id:"i1",order_id:"order-1",title:"Test",position:1,required:true,completed:false,note:null,completed_by:null,completed_at:null}]});const snapshot=await new SupabaseOperationsRepository(fixture.client as never).load();expect(snapshot.orders[0]).toMatchObject({orderNo:"ORDER1",technicianId:"tech-john",branch:"Kuala Lumpur"});expect(snapshot.orders[0].checklist).toHaveLength(1)});
  it("hydrates structured address parts",async()=>{const fixture=clientFixture({orders:[{id:"order-1",order_no:"ORDER1",customer_name:"Mei",customer_phone:"6012",address:"12, Jalan Sejuk, Shah Alam",building:"12",address_line_1:"Jalan Sejuk",address_line_2:null,postcode:"40100",city:"Shah Alam",state:"Selangor",problem_description:"Leak",service_type:"Repair",quoted_price:260,assigned_technician_id:"20000000-0000-0000-0000-000000000004",branch_id:"b1",scheduled_at:null,admin_notes:null,status:"In Progress",version:2,created_at:"2026-08-14T00:00:00Z"}]});const snapshot=await new SupabaseOperationsRepository(fixture.client as never).load();expect(snapshot.orders[0]).toMatchObject({address:"12, Jalan Sejuk, Shah Alam",building:"12",address1:"Jalan Sejuk",postcode:"40100",city:"Shah Alam",state:"Selangor"})});
  it("hydrates audit events as readable labels and diffs",async()=>{const fixture=clientFixture({audit_events:[{id:1,order_id:"order-1",actor_id:"20000000-0000-0000-0000-000000000004",action:"order.completed",before_values:{status:"In Progress",version:5,order_no:"ORDER1"},after_values:{status:"Job Done",version:6,order_no:"ORDER1"},created_at:"2026-08-15T00:00:00Z"}]});const snapshot=await new SupabaseOperationsRepository(fixture.client as never).load();expect(snapshot.orders[0].audit).toEqual([{id:"1",action:"Job completed",actor:"John",at:"2026-08-15T00:00:00Z",detail:"Job marked done.",changes:[{label:"Status",before:"In Progress",after:"Job Done"}]}])});
  it("sends current version and scoped mutation parameters",async()=>{const fixture=clientFixture();await new SupabaseOperationsRepository(fixture.client as never).assign(order,"tech-ali");expect(fixture.rpc).toHaveBeenCalledWith("assign_order",{p_order_id:"order-1",p_technician_id:"20000000-0000-0000-0000-000000000003",p_expected_version:2})});
  it("updates service details with structured address through rpc",async()=>{const fixture=clientFixture();await new SupabaseOperationsRepository(fixture.client as never).updateOrderDetails(order,{serviceType:"Cleaning",customerPhone:"0123456789",address:"22, Jalan Baru, Kuala Lumpur",scheduledAt:"2026-08-20T02:00:00Z",building:"22",address1:"Jalan Baru",postcode:"50000",city:"Kuala Lumpur",state:"WP Kuala Lumpur"});expect(fixture.rpc).toHaveBeenCalledWith("update_order_details",{p_order_id:"order-1",p_expected_version:2,p_service_type:"Cleaning",p_customer_phone:"0123456789",p_address:"22, Jalan Baru, Kuala Lumpur",p_scheduled_at:"2026-08-20T02:00:00Z",p_building:"22",p_address_line_1:"Jalan Baru",p_address_line_2:null,p_postcode:"50000",p_city:"Kuala Lumpur",p_state:"WP Kuala Lumpur"})});
  it("attaches receipt evidence to recorded payments",async()=>{const fixture=clientFixture();await new SupabaseOperationsRepository(fixture.client as never).recordPayment(order,100,"Cash",undefined,"ev-1");expect(fixture.rpc).toHaveBeenCalledWith("record_payment",{p_order_id:"order-1",p_expected_version:2,p_amount:100,p_method:"Cash",p_notes:null,p_receipt_evidence_id:"ev-1"})});
  it("passes receipt evidence through completion",async()=>{const fixture=clientFixture();await new SupabaseOperationsRepository(fixture.client as never).complete(order,{workDone:"Repaired",extraCharges:0,paymentAmount:100,paymentMethod:"Cash",receiptEvidenceId:"ev-1"});expect(fixture.rpc).toHaveBeenCalledWith("complete_order",{p_order_id:"order-1",p_expected_version:2,p_work_done:"Repaired",p_extra_charges:0,p_remarks:null,p_payment_amount:100,p_payment_method:"Cash",p_receipt_evidence_id:"ev-1"})});
  it("surfaces authorization errors",async()=>{const fixture=clientFixture();fixture.rpc.mockResolvedValueOnce({data:null,error:{message:"Admin access required"}});await expect(new SupabaseOperationsRepository(fixture.client as never).close(order)).rejects.toThrow("Admin access required")});
  it("normalizes stale-version errors",async()=>{const fixture=clientFixture();fixture.rpc.mockResolvedValueOnce({data:null,error:{message:"STALE_VERSION"}});await expect(new SupabaseOperationsRepository(fixture.client as never).start(order)).rejects.toThrow("Refresh and try again")});
  it("refreshes on subscribe/realtime and cleans up",()=>{vi.useFakeTimers();const fixture=clientFixture();const refresh=vi.fn();const unsubscribe=new SupabaseOperationsRepository(fixture.client as never).subscribe(refresh);expect(refresh).toHaveBeenCalledTimes(1);fixture.handlers[0]();vi.advanceTimersByTime(120);expect(refresh).toHaveBeenCalledTimes(2);unsubscribe();expect(fixture.removeChannel).toHaveBeenCalled();vi.useRealTimers()});
});
